/* ═══════════════════════════════════════════════════════════════════════════
   THE STANDARD SIM ANSWER — the core's own fold of a committed archive.

   `wallflowers-sim.cbor`, beside this file, is core-wasm's `hand_built()` archive,
   held to it by the core-wasm test `the_sim_archive_is_the_hand_built_one`. This
   folds it with the wasm just built and writes the producer's answer, exactly as
   object.fold shapes one, with `fixture: true`. A site feeds it to
   WallflowersClient.sim() to draw before a keyholder is up, and the model says it
   is a fixture. Nobody hand-writes fold output: when a view changes, the next
   stage regenerates this from the new fold.

   TWO ARCHIVES, each pinned in core-wasm (the_sim_archive_is_the_hand_built_one):
     wallflowers-sim       hand_built(): a small account, with two objects refused
     wallflowers-sim-site  site_built(): a Site as a site draws one — offices, an
                           affiliation, a hosted forum with a room, a notebook, an
                           event with a ticket link — every op written through
                           the door. Invented text only.
   Each is written TWICE: .json for fetch(), and .js, a classic script that sets
   self.WallflowersSimAnswer, for a page on another origin that a fetch cannot
   reach (the docs server sends no CORS header).

   Run by account/stage.sh:  node ../shared/gen-sim.mjs <out-dir>
   ═══════════════════════════════════════════════════════════════════════════ */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { webcrypto } from 'node:crypto';

const here = path.dirname(fileURLToPath(import.meta.url));
export const ARCHIVE = path.join(here, 'wallflowers-sim.cbor');
export const ARCHIVES = { 'wallflowers-sim': ARCHIVE, 'wallflowers-sim-site': path.join(here, 'wallflowers-sim-site.cbor') };
export const CORE = path.join(here, '..', 'docs', 'core', 'core_wasm_bg.wasm');

/* The core's fold_archive over `bytes`: the raw producer answer, parsed. With
   `withOn`, also the core's ops_on (which kinds each op may be written onto), so
   a sim can answer capabilities the way a keyholder does. */
export async function foldArchive(wasmPath, bytes, withOn) {
  const mod = await WebAssembly.compile(fs.readFileSync(wasmPath));
  let inst;
  const imports = {};
  for (const i of WebAssembly.Module.imports(mod)) {
    (imports[i.module] ||= {})[i.name] = i.name === 'pacific_fill_random'
      ? (ptr, len) => { webcrypto.getRandomValues(new Uint8Array(inst.exports.memory.buffer, ptr, len)); return 0; }
      : () => 0;
  }
  inst = await WebAssembly.instantiate(mod, imports);
  const core = inst.exports;
  const ptr = core.alloc(bytes.length);
  new Uint8Array(core.memory.buffer, ptr, bytes.length).set(bytes);
  const n = core.fold_archive(bytes.length);
  // Read after the call: a fold that grows memory detaches any view taken before.
  const text = new TextDecoder().decode(new Uint8Array(core.memory.buffer, core.out_ptr(), core.erred() ? core.out_len() : n));
  if (core.erred()) throw new Error('the core refused the sim archive: ' + text);
  const answer = JSON.parse(text);
  if (withOn) {
    const m = core.ops_on();
    answer.ops_on = JSON.parse(new TextDecoder().decode(new Uint8Array(core.memory.buffer, core.out_ptr(), m)));
  }
  return answer;
}

export async function simAnswer(wasmPath = CORE, archive = ARCHIVE) {
  const answer = await foldArchive(wasmPath, new Uint8Array(fs.readFileSync(archive)), true);
  answer.fixture = true;
  answer._note = 'A FIXTURE. The core\'s own fold of ' + path.basename(archive) +
    ' (product/app/web/shared/), pinned to its builder in core-wasm. Nothing here is anyone\'s account.';
  return answer;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dir = process.argv[2];
  if (!dir) { console.error('usage: node gen-sim.mjs <out-dir>'); process.exit(2); }
  for (const [name, archive] of Object.entries(ARCHIVES)) {
    const a = await simAnswer(CORE, archive);
    const json = JSON.stringify(a, null, 1);
    fs.writeFileSync(path.join(dir, name + '.json'), json + '\n');
    fs.writeFileSync(path.join(dir, name + '.js'),
      '/* A FIXTURE, generated by product/app/web/shared/gen-sim.mjs. Do not edit. */\n' +
      'self.WallflowersSimAnswer = ' + json + ';\n');
    console.log(`  sim    ${dir}/${name}.{json,js} (${a.groups.length} objects, ${a.rejected.length} refused, fixture)`);
  }
}
