//! Turn the ARC_BUILD_* environment into plain Rust string literals.
//!
//! WHY A BUILD SCRIPT AND NOT `option_env!`. Two reasons, and the second is the load-bearing one.
//!
//!  1. `concat!` cannot take an `option_env!`, so a single greppable marker line — the thing that
//!     lets `strings /opt/arc/bin/node` answer "which commit is this?" without running it — has to
//!     be assembled somewhere that can do string work. That is here.
//!
//!  2. FINGERPRINTING. A stamp that cargo can serve from cache is not a stamp; it is last week's
//!     SHA on this week's binary, which is worse than no stamp at all because it looks right.
//!     `rerun-if-env-changed` makes the SHA a declared input of this crate, so changing it
//!     recompiles arc-build and relinks every plane that carries it. (rustc does emit env-deps
//!     for `option_env!` too, but this states the dependency instead of relying on it.)
//!
//! Nothing here fails a build: an unset ARC_BUILD_SHA is a legitimate local `cargo build`, and
//! the crate's job is then to make the binary SAY it is unstamped, not to refuse to exist.

use std::{env, fs, path::Path};

/// Read a build var, trimmed, with empty treated as absent.
fn var(key: &str) -> Option<String> {
    println!("cargo:rerun-if-env-changed={key}");
    env::var(key).ok().map(|s| s.trim().to_string()).filter(|s| !s.is_empty())
}

/// Escape for embedding inside a Rust `"..."` literal. These values come from `git` on the
/// deploying laptop, not from a stranger, but a generated source file that can be broken by its
/// own input is a trap waiting for the first branch name with a quote in it.
fn lit(s: &str) -> String {
    s.escape_default().to_string()
}

fn main() {
    let sha = var("ARC_BUILD_SHA");
    let git_ref = var("ARC_BUILD_REF").unwrap_or_else(|| "unknown".into());
    let built = var("ARC_BUILD_TIME").unwrap_or_else(|| "unknown".into());
    // The sibling pacific checkout the workspace [patch] compiled in — see lib.rs on why the
    // arc SHA alone does not describe these binaries.
    let core = var("ARC_BUILD_CORE").unwrap_or_else(|| "unknown".into());
    let dirty = matches!(var("ARC_BUILD_DIRTY").as_deref(), Some("1" | "true" | "yes"));

    let stamped = sha.is_some();
    let sha = sha.unwrap_or_else(|| "unknown".into());
    let short: String = sha.chars().take(12).collect();

    // ONE line, greppable out of the binary with `strings`. The `@(#)` prefix is the old SCCS
    // `what(1)` marker — chosen because it is vanishingly unlikely to collide with anything else
    // in a 10MB binary, so `strings node | grep '@(#)arc'` is an exact search.
    let marker = format!(
        "@(#)arc-build commit={sha} ref={git_ref} dirty={dirty} core={core} built={built} stamped={stamped}"
    );

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("stamp.rs");
    fs::write(
        &out,
        format!(
            "// Generated by lib/arc-build/build.rs. Do not edit; it is rewritten every build.\n\
             pub const COMMIT: &str = \"{}\";\n\
             pub const SHORT: &str = \"{}\";\n\
             pub const REF: &str = \"{}\";\n\
             pub const DIRTY: bool = {};\n\
             pub const CORE: &str = \"{}\";\n\
             pub const BUILT: &str = \"{}\";\n\
             pub const STAMPED: bool = {};\n\
             pub const MARKER: &str = \"{}\";\n",
            lit(&sha),
            lit(&short),
            lit(&git_ref),
            dirty,
            lit(&core),
            lit(&built),
            stamped,
            lit(&marker),
        ),
    )
    .expect("write stamp.rs");
}
