"""emitter — obtain a LIVE intro blob by driving the REAL pairing path.

THERE IS NO FALLBACK IN THIS MODULE, AND THAT IS THE POINT.

The thing this harness gates is a change to `node.rs`. The E10 tripwire is the
acceptance test for The Build's D-E and A5, so its whole value is that it STOPS
PASSING the day those land. Two ways to destroy that value:

  1. Attack a blob some bespoke helper sealed with `seal::seal(&p, &t, &t)` itself.
     That blob opens from its tag forever, whatever node.rs does. (Fixed by making
     `intro_emit` call `Node::pair_scan_why` / `Node::group_add_member` instead.)

  2. Fall back to a pre-recorded blob when the live one cannot be obtained, and
     report the result as though it were live. A landed fix looks EXACTLY like
     "the emitter did not run" — `seal()` starts refusing `tag == secret`, or the
     payload stops being sealed to the tag — so a fallback would report "still
     vulnerable" forever, which is the one answer that must never be wrong.

So: every failure here raises `EmitterUnavailable`, carrying the real cargo or
process output. A caller that cannot get a live blob has NO VERDICT. It must say
so and refuse to grade, never guess.

The emitter binary is a standalone crate at `intro_emit/` — deliberately NOT a
`cargo example` under core/, because examples are on every other track's
`cargo test` build path. See intro_emit/Cargo.toml.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent
# HERE is core/harness/adversary, so parents[1] is core itself — the harness moved
# inside core on 18 Sep 2026, and the paths below are core-relative now.
CORE_ROOT = HERE.parents[1]
CRATE = HERE / "intro_emit"
BIN = CRATE / "target" / "debug" / "intro_emit"
CARGO = Path(os.path.expanduser("~/.cargo/bin/cargo"))
BUILD_TIMEOUT = 1800  # a cold build of pacific-core + mls-rs is not quick
RUN_TIMEOUT = 180

# core/.cargo/config.toml carries this machine's local patch paths (it is gitignored
# there for exactly that reason). Patches apply at a WORKSPACE ROOT only, and this
# crate is its own workspace, so they have to be restated here or the graph will not
# resolve. `relay` is skipped: it is a DEV-dependency of pacific-core, which Cargo
# does not resolve for a path dependency, and pulling it in would couple this build
# to the arc workspace for no gain.
_SKIP_PATCHED_CRATES = {"relay"}


class EmitterUnavailable(RuntimeError):
    """No live intro blob could be produced. NOT a verdict — an absence of one.

    `phase` is "build" or "run". It matters: a RUN failure can be the fix landing
    (A5 makes node.rs:319 return Err, so the emitter dies), while a BUILD failure is
    only ever a broken tree. Reading a cargo error that happens to mention seal.rs as
    "the fix landed" would be the same laundering pointed the other way.
    """

    def __init__(self, message: str, phase: str = "run"):
        super().__init__(message)
        self.phase = phase


def _cargo() -> str:
    if CARGO.exists():
        return str(CARGO)
    found = shutil.which("cargo")
    if not found:
        raise EmitterUnavailable(
            "cargo is not on PATH and ~/.cargo/bin/cargo does not exist, so the "
            "emitter cannot be built. `export PATH=\"$HOME/.cargo/bin:$PATH\"`.",
            phase="build",
        )
    return found


def sync_cargo_config() -> Path | None:
    """Mirror core's local-only [patch] tables into this crate's own cargo config.

    Relative paths in core's config are relative to core/; they are rewritten to
    absolute so they still point at the same checkouts from here. Returns the path
    written, or None when core has no local config (the git sources then resolve
    normally).
    """
    src = CORE_ROOT / ".cargo" / "config.toml"
    dst = CRATE / ".cargo" / "config.toml"
    if not src.is_file():
        return None
    import tomllib

    doc = tomllib.loads(src.read_text())
    patch = doc.get("patch", {})
    lines = [
        "# GENERATED by harness/adversary/emitter.py from core/.cargo/config.toml.",
        "# Machine-local patch paths, made absolute. Do not edit; do not commit.",
        "",
    ]
    for source, crates in patch.items():
        kept = {
            name: spec
            for name, spec in crates.items()
            if name not in _SKIP_PATCHED_CRATES and isinstance(spec, dict) and "path" in spec
        }
        if not kept:
            continue
        lines.append(f'[patch."{source}"]')
        for name, spec in kept.items():
            p = Path(spec["path"])
            if not p.is_absolute():
                p = (CORE_ROOT / p).resolve()
            lines.append(f'{name} = {{ path = "{p}" }}')
        lines.append("")
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines))
    return dst


def build() -> Path:
    """Build `intro_emit` against the tree AS IT IS NOW. Raises, never falls back.

    Cargo runs on EVERY call, on purpose. It is incremental and a no-op build costs a
    fraction of a second, and the alternative — reusing a binary compiled against an
    older `node.rs` — is a slow-motion version of the fixture fallback: the tripwire
    would grade yesterday's bytes and never notice the fix land.

    `INTRO_EMIT_BIN` (an explicit path) and `INTRO_EMIT_NO_BUILD` (reuse what is
    already built) both exist for driving this harness from somewhere else. Neither is
    a fallback: they are only honoured when the caller set them, and a missing binary
    is still a refusal to grade.
    """
    override = os.environ.get("INTRO_EMIT_BIN")
    if override:
        p = Path(override)
        if not p.is_file():
            raise EmitterUnavailable(
                f"INTRO_EMIT_BIN={override} is not a file", phase="build"
            )
        return p
    if os.environ.get("INTRO_EMIT_NO_BUILD"):
        if not BIN.is_file():
            raise EmitterUnavailable(
                f"INTRO_EMIT_NO_BUILD is set but there is no emitter at {BIN}",
                phase="build",
            )
        return BIN
    sync_cargo_config()
    try:
        r = subprocess.run(
            [_cargo(), "build", "--bin", "intro_emit"],
            cwd=CRATE,
            capture_output=True,
            text=True,
            timeout=BUILD_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        raise EmitterUnavailable(
            f"`cargo build` in {CRATE} did not finish in {BUILD_TIMEOUT}s", phase="build"
        ) from None
    if r.returncode != 0:
        raise EmitterUnavailable(
            f"`cargo build --bin intro_emit` failed in {CRATE} (rc={r.returncode}).\n"
            "The emitter compiles against pacific-core's PUBLIC API, so this is either a\n"
            "broken tree or an API change — read the error before assuming either.\n"
            f"--- cargo stdout (tail) ---\n{r.stdout[-3000:]}\n"
            f"--- cargo stderr (tail) ---\n{r.stderr[-4000:]}",
            phase="build",
        )
    if not BIN.is_file():
        raise EmitterUnavailable(
            f"cargo reported success but there is no binary at {BIN}", phase="build"
        )
    return BIN


# A landed A5 ("seal() refuses tag == secret") makes node.rs:319 return Err, so the
# emitter EXITS NON-ZERO instead of publishing an unopenable blob. That is a fix, not
# a broken harness, and the caller must be told which it is looking at.
_FIX_SIGNATURES = ("Seal(", "seal:", "conn_secret", "dest_tag", "tag == secret")


def looks_like_the_fix(output: str) -> bool:
    """Does this emitter failure read like A5 refusing `tag == secret`?"""
    low = output.lower()
    return "seal" in low and any(s.lower() in low for s in _FIX_SIGNATURES)


def emit(scenario: str, relay_url: str | None = None, **kw) -> dict:
    """Run one emitter scenario; return its ground-truth JSON. Raises, never guesses."""
    binary = build()
    argv = [str(binary), "--scenario", scenario]
    if relay_url:
        argv += ["--relay", relay_url]
    for k, v in kw.items():
        argv += [f"--{k.replace('_', '-')}", str(v)]
    try:
        r = subprocess.run(argv, capture_output=True, text=True, timeout=RUN_TIMEOUT)
    except subprocess.TimeoutExpired:
        raise EmitterUnavailable(
            f"intro_emit --scenario {scenario} hung for {RUN_TIMEOUT}s (relay reachable?)"
        ) from None
    if r.returncode != 0:
        combined = r.stdout + "\n" + r.stderr
        hint = (
            "\nTHIS READS LIKE THE FIX: the emitter died inside the seal, which is what\n"
            "A5 (seal() rejecting tag == secret) does to node.rs:319/:632. If D-E/A5 have\n"
            "landed, update the tripwire — do not repair the emitter.\n"
            if looks_like_the_fix(combined)
            else ""
        )
        raise EmitterUnavailable(
            f"intro_emit --scenario {scenario} failed (rc={r.returncode}).{hint}\n"
            f"--- stdout ---\n{r.stdout[-2000:]}\n--- stderr ---\n{r.stderr[-4000:]}"
        )
    lines = [l for l in r.stdout.splitlines() if l.startswith("{")]
    if not lines:
        raise EmitterUnavailable(
            f"intro_emit --scenario {scenario} printed no JSON.\n"
            f"--- stdout ---\n{r.stdout[-2000:]}\n--- stderr ---\n{r.stderr[-2000:]}"
        )
    truth = json.loads(lines[-1])
    truth["source"] = f"LIVE: {truth.get('via', scenario)} -> {truth.get('call_site', '?')}"
    return truth


def nonce(prefix: str) -> str:
    """A token no implementation can guess, hardcode, or re-derive.

    Recovering one of these out of relay ciphertext is the proof that the Python
    adversary opened something rather than restated something it was handed.
    """
    return f"{prefix}-{uuid.uuid4().hex}"
